name: Go CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  check-and-test:
    name: Check, Build, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Vet packages
        run: make vet

      - name: Run compiler unit tests
        run: make test

      - name: Run sandbox tests
        run: make sandbox-test
