name: lint

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

permissions:
  contents: read
  pull-requests: read
  statuses: write

jobs:
  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint (root)
        run: $(go env GOPATH)/bin/golangci-lint run ./...

      - name: Run golangci-lint (integration)
        run: |
          cd integration
          $(go env GOPATH)/bin/golangci-lint run ./...
